### ISSUE TITLE
Individual Cell callback

### ISSUE THREAD

**Issue by CodeMaven** [walkframe/react-gridsheet#15]
I'm looking at this component for use as a spreadsheet in my application. I will attach my own server-side evaluator to it. For my purpose I need to send every change to the server - but I don't want to send the whole matrix (which will be very big) to the server each time. It would be helpful if in the onChange event we could get an indicator of what cell actually changed so I can send just that cell value to the server. Perhaps just the x/y array indexes of the cell that changed.

**Comment by righ** [comment]
Thank you for your issues.
I will handle it.

**Comment by righ** [comment]
I added `positions` argument to onChange, onSave and onSelect (new).
Check and close the issues if your problems have been resolved.

**Comment by CodeMaven** [comment]
Perfect, that works great for me.
