### ISSUE TITLE
Editing cell shows [object Object] / custom editor?

### ISSUE THREAD

**Issue by CodeMaven** [walkframe/react-gridsheet#17]
All of my cells contain objects, something like:
{
key: 'A3',
calculatedValue: 23,
formula: '=A1+A2',
style: {
"bold": true,
"fontSize: 14
},
format: {
"type": "number",
"decimalPlaces: 4
}
}

I have a custom renderer that renders only the calculatedValue field in a , and a custom parser that reads a string and converts it to an object as above.

However, there are two serious issues:

The parser has no reference to either the previous value or the cell indexes in the matrix so I have no way of looking up the other existing values (such as the current style) in order to make sure that I update the cell appropriately without changing it's style. If a person enters "=A1+B1" that comes in as a string, I need to determine that's a formula in my parser, and send it off to my calculator to get a calculated value to update, which I would like to do asynchronously. I also need to get the existing style so I can return a new object that has the new correct values including the same style.

If I go to a cell and just start typing it seems to handle it as a string and displays what I am typing, overwriting anything that's currently there - this behaviour is fine. However, if I double click on the cell it shows [object Object] in the cell as the existing value. This needs to be properly parsed to show either the formula or literal value, depending on what's actually in the object. I think this needs a way to specify a custom cell editor and I do not see any way to do that.

**Comment by righ** [comment]
Sorry for my late dealing.
I added the stringify on renderer and callback on parser.
Try them like the following:
https://github.com/walkframe/react-gridsheet/blob/v0.5.7/index.stories.tsx#L9-L23

I am going to write the usage on document in a few days.
