### ISSUE TITLE
Parser behavior when copying to multiple cells

### ISSUE THREAD

**Issue by yryrgogo** [walkframe/react-gridsheet#19]
What is the copy behavior when I set a function to be validated by parser in column?
For example, if I copy from the clipboard to multiple cells starting from A1, the validation function in parser will be applied to all cells in the copy range.
The desired behavior would be to apply the parser's validation only to the cells in column A.
When copying multiple cells at once, it would be nice if the parser for each cell was applied at the same time.

It would be better if I could fix it myself, but now I'm using the matrix and positions passed to onChange to validate the selected cells without using the parser.

**Comment by righ** [comment]
Thank you for your issue.

I think I've fixed it in the latest version(v0.5.7).
Please try it.

**Comment by yryrgogo** [comment]
Thanks for the quick response!
I just tried new version and it works as I ideally want it to.
Now I can implement validation and arbitrary processing in each cell with the parser.
